# -*- coding: utf-8 -*-
"""
Master Scene Manifest for 4D-Crypto-Risk Documentary
Defines exactly 165 motion-graphical scenes across all 7 acts.
Each scene has a distinct animation archetype, visual telemetry, and narrative mapping.
"""

SCENE_MANIFEST = [
    # ================================================= ACT 0: PROLOGUE & HOOK (Scenes 001-025) ===
    {"id": 1, "name": "s001_channel_ident", "act": 0, "type": "channel_ident", "title": "IZHAAN INTELLECT", "subtitle": "CINEMATIC SCIENCE & QUANTITATIVE RESEARCH"},
    {"id": 2, "name": "s002_glitch_warning", "act": 0, "type": "title_card", "title": "SYSTEMIC CRISIS FORENSICS", "subtitle": "MATHEMATICAL COLLAPSE OF CRYPTO LEVERAGE"},
    {"id": 3, "name": "s003_51pct_crash_reveal", "act": 0, "type": "candlestick", "title": "BITCOIN 2024-2026", "subtitle": "MAX DRAWDOWN: -51.32% PORTFOLIO EVAPORATION"},
    {"id": 4, "name": "s004_liquidation_cascade", "act": 0, "type": "orderbook", "title": "LIQUIDATION CASCADE", "subtitle": "BINANCE DERIVATIVES ENGINE // 100K+ ACCOUNTS FLUSHED"},
    {"id": 5, "name": "s005_panic_telemetry", "act": 0, "type": "terminal_telemetry", "title": "PANIC METRICS", "subtitle": "PERP FUNDING: -0.048% // DVOL IMPLODING"},
    {"id": 6, "name": "s006_central_bank_promise", "act": 0, "type": "title_card", "title": "THE CENTRAL BANK PROMISE", "subtitle": "DECIMAL-POINT PRECISION IN UNPRECEDENTED CRISES"},
    {"id": 7, "name": "s007_state_space_equations", "act": 0, "type": "circuit_board", "title": "DYNAMIC LINEAR MODELS", "subtitle": "x_{t} = G x_{t-1} + w_{t} // y_{t} = F x_{t} + v_{t}"},
    {"id": 8, "name": "s008_kalman_origins", "act": 0, "type": "kalman", "title": "KALMAN FILTERING (1960)", "subtitle": "FROM APOLLO GUIDANCE TO SYSTEMIC CONTAGION"},
    {"id": 9, "name": "s009_hypercube_glimpse", "act": 0, "type": "tesseract", "title": "THE 4TH DIMENSION", "subtitle": "PROJECTING 4-MANIFOLD TENSORS INTO 1-D ACTION"},
    {"id": 10, "name": "s010_academic_illusion", "act": 0, "type": "title_card", "title": "THE ACADEMIC ILLUSION", "subtitle": "WHY 90% BACKTEST ACCURACY GUARANTEES RUIN"},
    {"id": 11, "name": "s011_live_exchange_pipe", "act": 0, "type": "terminal_telemetry", "title": "POINT-IN-TIME INGESTION", "subtitle": "BINANCE REST API + DERIBIT DVOL + FRED MACRO"},
    {"id": 12, "name": "s012_970_day_history", "act": 0, "type": "candlestick", "title": "970 DAILY OBSERVATIONS", "subtitle": "STRICT AS-OF ISOLATION (JAN 2024 -> SEP 2026)"},
    {"id": 13, "name": "s013_circularity_teaser", "act": 0, "type": "radar_gauge", "title": "THE CIRCULARITY TRAP", "subtitle": "REGRESSING REALITY ON A MIRROR"},
    {"id": 14, "name": "s014_the_hedged_solution", "act": 0, "type": "candlestick", "title": "DODGING THE 51% CRASH", "subtitle": "WALK-FORWARD PERPETUAL HEDGE // MDD CUT TO 12.95%"},
    {"id": 15, "name": "s015_plot_twist_teaser", "act": 0, "type": "title_card", "title": "THE PLOT TWIST", "subtitle": "HOW A 1-LINE DUMB RULE BEAT MACHINE LEARNING"},
    {"id": 16, "name": "s016_mandelbrot_ghost", "act": 0, "type": "circuit_board", "title": "VOLATILITY CLUSTERING", "subtitle": "BENOIT MANDELBROT (1963) // FAT TAILS IN CRYPTO"},
    {"id": 17, "name": "s017_hysteresis_preview", "act": 0, "type": "hysteresis", "title": "SCHMITT-TRIGGER HYSTERESIS", "subtitle": "DUAL-THRESHOLD FLIP REDUCTION IN LIVE EXECUTION"},
    {"id": 18, "name": "s018_title_sequence_a", "act": 0, "type": "tesseract", "title": "THE 51% ILLUSION", "subtitle": "AN IZHAAN INTELLECT ORIGINAL INVESTIGATION"},
    {"id": 19, "name": "s019_title_sequence_b", "act": 0, "type": "title_card", "title": "PART I: THE CENTRAL BANK MACHINE", "subtitle": "THE MATHEMATICS OF MULTIDISCIPLINARY RISK"},
    {"id": 20, "name": "s020_radar_scan_intro", "act": 0, "type": "radar_gauge", "title": "FOUR-DIMENSIONAL SPACE", "subtitle": "LIQUIDITY // DERIVATIVES // VOLATILITY // MACRO"},
    {"id": 21, "name": "s021_price_fallacy", "act": 0, "type": "candlestick", "title": "THE REARVIEW MIRROR", "subtitle": "WHY SPOT PRICE ACTION LAGS REAL COLLAPSE"},
    {"id": 22, "name": "s022_funding_fallacy", "act": 0, "type": "orderbook", "title": "THE LEVERAGE ILLUSION", "subtitle": "FUNDING RATES BLIND TO OFF-CHAIN CONTAGION"},
    {"id": 23, "name": "s023_macro_silos", "act": 0, "type": "contagion", "title": "INSTITUTIONAL SILOS", "subtitle": "WALL STREET BLIND TO CRYPTO // CRYPTO BLIND TO RATES"},
    {"id": 24, "name": "s024_enter_4d_mgrff", "act": 0, "type": "circuit_board", "title": "4D-MGRFF SUITE", "subtitle": "UNIFYING FRAGMENTED RISK ECOSYSTEMS"},
    {"id": 25, "name": "s025_act1_transition", "act": 0, "type": "title_card", "title": "ACT I // THE ARCHITECTURE", "subtitle": "CALIBRATING THE UNSEEN STRESS TENSOR"},

    # ============================================ ACT 1: THE CENTRAL BANK MATH (Scenes 026-055) ===
    {"id": 26, "name": "s026_four_pillars_grid", "act": 1, "type": "radar_gauge", "title": "THE 4 SYSTEMIC PILLARS", "subtitle": "CROSS-DISCIPLINARY HIGH-DIMENSIONAL OBSERVATION"},
    {"id": 27, "name": "s027_pillar_1_liquidity", "act": 1, "type": "orderbook", "title": "PILLAR 1: MICROSTRUCTURE", "subtitle": "TOP-10 LEVEL DEPTH // BID-ASK ASYMMETRY"},
    {"id": 28, "name": "s028_pillar_2_derivatives", "act": 1, "type": "terminal_telemetry", "title": "PILLAR 2: LEVERAGE", "subtitle": "PERPETUAL BASIS // 8-HOUR FUNDING RATES"},
    {"id": 29, "name": "s029_pillar_3_volatility", "act": 1, "type": "candlestick", "title": "PILLAR 3: TAIL VOLATILITY", "subtitle": "DERIBIT DVOL 30-DAY FORWARD IMPLIED VOLATILITY"},
    {"id": 30, "name": "s030_pillar_4_macro", "act": 1, "type": "contagion", "title": "PILLAR 4: MACRO SPILLOVER", "subtitle": "CBOE VIX + 10Y US TREASURY + CREDIT SPREADS"},
    {"id": 31, "name": "s031_latent_state_concept", "act": 1, "type": "circuit_board", "title": "THE UNSEEN FEVER: S_t", "subtitle": "SYSTEMIC STRESS AS AN UNOBSERVABLE MANIFOLD"},
    {"id": 32, "name": "s032_kalman_prediction", "act": 1, "type": "kalman", "title": "TIME UPDATE STEP", "subtitle": "x_{t|t-1} = G_t x_{t-1|t-1} // P_{t|t-1} = G P G^T + Q"},
    {"id": 33, "name": "s033_kalman_innovation", "act": 1, "type": "kalman", "title": "INNOVATION RESIDUAL", "subtitle": "y_{t} - F_t x_{t|t-1} // REALITY VS PRIOR BELIEF"},
    {"id": 34, "name": "s034_kalman_gain", "act": 1, "type": "kalman", "title": "OPTIMAL KALMAN GAIN", "subtitle": "K_t = P F^T (F P F^T + R)^{-1}"},
    {"id": 35, "name": "s035_huber_robustness_curve", "act": 1, "type": "circuit_board", "title": "HUBER ROBUST LOSS", "subtitle": "LINEAR PENALTY FOR FLASH CRASH RESIDUALS |e| > k"},
    {"id": 36, "name": "s036_em_q_estimation", "act": 1, "type": "terminal_telemetry", "title": "EM-ALGORITHM ESTIMATION", "subtitle": "SOLVING INNOVATION COVARIANCE Q WITHOUT GUESSWORK"},
    {"id": 37, "name": "s037_polarity_constraint", "act": 1, "type": "radar_gauge", "title": "POLARITY IDENTIFICATION", "subtitle": "LOCKING VIX FACTOR LOADING > 0 (NO SIGN FLIP)"},
    {"id": 38, "name": "s038_dgrs_trajectory_full", "act": 1, "type": "kalman", "title": "DGRS LATENT STRESS TRAJECTORY", "subtitle": "HISTORICAL STRESS S_t RECONSTRUCTION (2024-2026)"},
    {"id": 39, "name": "s039_august_2024_spike", "act": 1, "type": "candlestick", "title": "AUGUST 2024 UNWIND", "subtitle": "YEN CARRY COLLAPSE SPIKES S_t INTO CRITICAL BAND"},
    {"id": 40, "name": "s040_credible_intervals", "act": 1, "type": "kalman", "title": "BAYESIAN 95% CREDIBLE INTERVALS", "subtitle": "S_t +/- 1.96 * SQRT(P_{t|t}) DYNAMIC BOUNDS"},
    {"id": 41, "name": "s041_tesseract_rotation_fast", "act": 1, "type": "tesseract", "title": "HIGHER-DIMENSIONAL EMBEDDING", "subtitle": "REDUCING 4D MULTIDISCIPLINARY TENSORS"},
    {"id": 42, "name": "s042_so4_plane_projection", "act": 1, "type": "tesseract", "title": "SO(4) ROTATION PLANES", "subtitle": "SIMULTANEOUS DOUBLE ROTATIONS IN 4-SPACE"},
    {"id": 43, "name": "s043_hyperplane_slicing", "act": 1, "type": "tesseract", "title": "CROSS-SECTIONAL SLICING", "subtitle": "OBSERVING 3D TIME SLICES OF 4D STRESS GEOMETRY"},
    {"id": 44, "name": "s044_terminal_diagnostics", "act": 1, "type": "terminal_telemetry", "title": "KALMAN STABILITY CHECK", "subtitle": "EIGENVALUES INSIDE UNIT CIRCLE // SPECTRUM STABLE"},
    {"id": 45, "name": "s045_bic_model_selection", "act": 1, "type": "duel_table", "title": "BIC FACTOR SELECTION", "subtitle": "1-FACTOR VS 2-FACTOR VS 3-FACTOR PENALTY"},
    {"id": 46, "name": "s046_one_factor_optimality", "act": 1, "type": "circuit_board", "title": "PARSIMONY PRINCIPLE", "subtitle": "1 LATENT FACTOR CAPTURES 73% OF COVARIANCE"},
    {"id": 47, "name": "s047_crypto_vs_fiat_diff", "act": 1, "type": "radar_gauge", "title": "THE CRYPTO PARADOX", "subtitle": "24/7 MARKETS // NO CIRCUIT BREAKERS // EXTREME VELOCITY"},
    {"id": 48, "name": "s048_continuous_clearing", "act": 1, "type": "orderbook", "title": "CONTINUOUS SETTLEMENT", "subtitle": "NO WEEKEND HALTS // LIQUIDATIONS RUN AUTONOMOUSLY"},
    {"id": 49, "name": "s049_central_bank_blindness", "act": 1, "type": "title_card", "title": "THE CENTRAL BANK BLINDSPOT", "subtitle": "MODELS CALIBRATED FOR T+2 FAILING ON T+0"},
    {"id": 50, "name": "s050_synthetic_vs_real", "act": 1, "type": "terminal_telemetry", "title": "GENUINE DATA INTEGRITY", "subtitle": "ZERO SYNTHETIC TOY ARTIFACTS IN PIPELINE"},
    {"id": 51, "name": "s051_state_vector_snapshot", "act": 1, "type": "kalman", "title": "FILTERED STATE AT RUNTIME", "subtitle": "REAL-TIME EXTRACTION ENGINE PASSING ALL LINTS"},
    {"id": 52, "name": "s052_huber_residual_plot", "act": 1, "type": "circuit_board", "title": "HUBER WEIGHT DOWNWEIGHTING", "subtitle": "FLASH TAILS CLIPPED BY 62% IN OBSERVATION STEP"},
    {"id": 53, "name": "s053_mathematical_hubris", "act": 1, "type": "title_card", "title": "THE ILLUSION OF CONTROL", "subtitle": "BEAUTIFUL FORMULAS VS UNFORGIVING EXCHANGES"},
    {"id": 54, "name": "s054_contagion_teaser", "act": 1, "type": "contagion", "title": "THE NEXT PUZZLE: PROPAGATION", "subtitle": "WHERE DOES THE TSUNAMI STRIKE FIRST?"},
    {"id": 55, "name": "s055_act2_transition", "act": 1, "type": "title_card", "title": "ACT II // THE CONTAGION MATRIX", "subtitle": "PESARAN-SHIN GENERALIZED IMPULSE RESPONSES"},

    # ================================= ACT 2: THE GENERALIZED CONTAGION MATRIX (Scenes 056-085) ===
    {"id": 56, "name": "s056_network_topology", "act": 2, "type": "contagion", "title": "INTER-DOMAIN TOPOLOGY", "subtitle": "MAPPING DIRECTED EDGES ACROSS SYSTEMIC ASSETS"},
    {"id": 57, "name": "s057_cholesky_problem", "act": 2, "type": "circuit_board", "title": "THE CHOLESKY TRAP", "subtitle": "TRIANGULAR DECOMPOSITION IMPOSES ARBITRARY CAUSALITY"},
    {"id": 58, "name": "s058_order_permutation_error", "act": 2, "type": "duel_table", "title": "VARIABLE ORDERING SENSITIVITY", "subtitle": "PERMUTING INPUTS ALTERS TRADITIONAL IRF BY 80%"},
    {"id": 59, "name": "s059_pesaran_shin_paper", "act": 2, "type": "title_card", "title": "PESARAN & SHIN (1998)", "subtitle": "GENERALIZED IMPULSE RESPONSE ANALYSIS IN LINEAR MODELS"},
    {"id": 60, "name": "s060_girf_formula_reveal", "act": 2, "type": "circuit_board", "title": "INVARIANT SHOCK INTEGRATION", "subtitle": "GI_x(h, delta_j) = (sigma_{jj})^{-1/2} A_h Sigma e_j"},
    {"id": 61, "name": "s061_propagation_matrix_h1", "act": 2, "type": "terminal_telemetry", "title": "PROPAGATION MATRIX Pi_1", "subtitle": "1-DAY HORIZON GENERALIZED SPILLOVER COEFFICIENTS"},
    {"id": 62, "name": "s062_diagonal_normalization", "act": 2, "type": "terminal_telemetry", "title": "DIAGONAL = 1.0000 EXACT", "subtitle": "MATHEMATICAL IDENTITY RIGOROUSLY SATISFIED"},
    {"id": 63, "name": "s063_heatmap_render_h1", "act": 2, "type": "radar_gauge", "title": "Pi_1 TRANSMISSION HEATMAP", "subtitle": "MAGNITUDE SPREAD: [-0.45 TO +0.51]"},
    {"id": 64, "name": "s064_vix_to_ethbtc_shock", "act": 2, "type": "contagion", "title": "VIX -> ETH/BTC RATIO: -0.45", "subtitle": "WALL STREET PANIC CRUSHES ALTCOIN RATIOS"},
    {"id": 65, "name": "s065_institutional_flight", "act": 2, "type": "candlestick", "title": "DIGITAL FLIGHT TO SAFETY", "subtitle": "TRADERS SELL ALTS INTO BTC BEFORE EXITING TO FIAT"},
    {"id": 66, "name": "s066_realized_to_implied_vol", "act": 2, "type": "contagion", "title": "BTC_REAL_VOL -> DVOL: +0.51", "subtitle": "SPOT REALIZED SWINGS TRANSMIT DIRECTLY TO OPTIONS"},
    {"id": 67, "name": "s067_eth_btc_price_lead", "act": 2, "type": "contagion", "title": "BTC_PRICE -> ETH/BTC: -0.38", "subtitle": "BITCOIN CORRECTIONS AMPLIFY ALTCOIN BLEEDING"},
    {"id": 68, "name": "s068_propagation_matrix_h7", "act": 2, "type": "terminal_telemetry", "title": "PROPAGATION MATRIX Pi_7", "subtitle": "7-DAY DECAY AND PERSISTENCE HORIZON"},
    {"id": 69, "name": "s069_horizon_decay_dynamics", "act": 2, "type": "kalman", "title": "SHOCK ABSORPTION CURVE", "subtitle": "CROSS-MARKET ELASTICITY DAMPENING OVER 7 DAYS"},
    {"id": 70, "name": "s070_no_saturation_artifacts", "act": 2, "type": "circuit_board", "title": "NUMERICAL INTEGRITY VERIFIED", "subtitle": "ZERO +/-0.99 ARTIFICIAL CLIPPING ARTIFACTS"},
    {"id": 71, "name": "s071_tesseract_unfolding", "act": 2, "type": "tesseract", "title": "UNFOLDING 4D NETWORKS", "subtitle": "DALI'S CORPUS HYPERCUBUS AS A GRAPH TOPOLOGY"},
    {"id": 72, "name": "s072_clifford_torus_motion", "act": 2, "type": "tesseract", "title": "CLIFFORD TORUS EMBEDDING", "subtitle": "SURFACE OF EQUAL DISTANCE IN 4-SPACE"},
    {"id": 73, "name": "s073_liquidity_drain_pathway", "act": 2, "type": "orderbook", "title": "THE LIQUIDITY VORTEX", "subtitle": "HOW OPTIONS MARKET MAKERS PULL SPOT BIDS"},
    {"id": 74, "name": "s074_deribit_delta_hedging", "act": 2, "type": "orderbook", "title": "GAMMA SQUEEZE SPILLOVER", "subtitle": "DERIBIT SHORT-GAMMA ACCELERATES DOWNSIDE CASKS"},
    {"id": 75, "name": "s075_funding_inversion_cue", "act": 2, "type": "terminal_telemetry", "title": "FUNDING INVERSION", "subtitle": "NEGATIVE BASIS SIGNALS RETAIL CAPITULATION"},
    {"id": 76, "name": "s076_the_macro_anchor", "act": 2, "type": "contagion", "title": "THE 10-YEAR YIELD ANCHOR", "subtitle": "DOLLAR COST OF CAPITAL RESTRAINING CRYPTO MARGIN"},
    {"id": 77, "name": "s077_contagion_summary_card", "act": 2, "type": "radar_gauge", "title": "Pi_h STRUCTURAL MAP SUMMARY", "subtitle": "VERIFIABLE DYNAMIC CONTAGION NETWORK CERTIFIED"},
    {"id": 78, "name": "s078_the_academic_confidence", "act": 2, "type": "title_card", "title": "PERFECT ON PAPER", "subtitle": "HIGH CORRELATION // COHERENT ECONOMIC LOGIC"},
    {"id": 79, "name": "s079_trading_signal_conversion", "act": 2, "type": "circuit_board", "title": "TURNING GRAPHS INTO TRADES", "subtitle": "CAN Pi_h PROTECT CAPITAL IN LIVE DEPLOYMENT?"},
    {"id": 80, "name": "s080_live_test_launch", "act": 2, "type": "candlestick", "title": "THE LIVE TOURNAMENT", "subtitle": "8 MODELS COMPETING ACROSS 292 ROLLING ORIGINS"},
    {"id": 81, "name": "s081_first_results_shock", "act": 2, "type": "terminal_telemetry", "title": "FIRST TOURNAMENT RUN", "subtitle": "M2 SINGLE-DOMAIN LOGISTIC CLAIMS BSS = +0.322"},
    {"id": 82, "name": "s082_suspicion_arises", "act": 2, "type": "title_card", "title": "TOO GOOD TO BE TRUE", "subtitle": "WHY DID A 1-VARIABLE MODEL CRUSH 4D TENSORS?"},
    {"id": 83, "name": "s083_code_audit_begins", "act": 2, "type": "terminal_telemetry", "title": "FORENSIC CODE AUDIT", "subtitle": "INSPECTING TARGET FORMULATION IN SOURCE CODE"},
    {"id": 84, "name": "s084_smoking_gun_found", "act": 2, "type": "circuit_board", "title": "THE SMOKING GUN", "subtitle": "y = (dvol >= quantile(0.85))"},
    {"id": 85, "name": "s085_act3_transition", "act": 2, "type": "title_card", "title": "ACT III // THE TRAP OF CIRCULARITY", "subtitle": "HOW ACADEMIC FINANCE TRICKS ITSELF"},

    # ================================= ACT 3: THE TRAP OF CIRCULARITY (Scenes 086-110) ===
    {"id": 86, "name": "s086_circularity_definition", "act": 3, "type": "title_card", "title": "STATISTICAL CIRCULARITY", "subtitle": "REGRESSING VOLATILITY ON MONOTONIC COPIES OF ITSELF"},
    {"id": 87, "name": "s087_target_diagram_old", "act": 3, "type": "circuit_board", "title": "THE FLAWED ARCHITECTURE", "subtitle": "INPUT: DVOL -> MODEL -> TARGET: DVOL >= 85TH %ILE"},
    {"id": 88, "name": "s088_fake_alpha_exposed", "act": 3, "type": "duel_table", "title": "THE ILLUSION OF ALPHA", "subtitle": "NOT PREDICTING CRASHES; PREDICTING PERSISTENCE"},
    {"id": 89, "name": "s089_lookahead_leak_card", "act": 3, "type": "candlestick", "title": "LOOKAHEAD BIAS UNCOVERED", "subtitle": "FULL-SAMPLE 85TH %ILE LEAKED 2026 DATA INTO 2024"},
    {"id": 90, "name": "s090_time_travel_crime", "act": 3, "type": "circuit_board", "title": "TIME-TRAVELER PREDICTION", "subtitle": "FUTURE HIGH VOLATILITY INFLATED PAST THRESHOLDS"},
    {"id": 91, "name": "s091_dismantling_the_rig", "act": 3, "type": "title_card", "title": "THE FORENSIC OVERHAUL", "subtitle": "ENFORCING THREE NON-NEGOTIABLE INTEGRITY RULES"},
    {"id": 92, "name": "s092_rule_1_target_decouple", "act": 3, "type": "candlestick", "title": "RULE 1: DECOUPLED DRAWDOWN", "subtitle": "TARGET = BTC SPOT MAX DRAWDOWN IN NEXT h DAYS"},
    {"id": 93, "name": "s093_rule_2_rolling_threshold", "act": 3, "type": "kalman", "title": "RULE 2: EXPANDING THRESHOLDS", "subtitle": "85TH %ILE RECOMPUTED DAILY STRICTLY ON PAST DATA"},
    {"id": 94, "name": "s094_rule_3_fdr_control", "act": 3, "type": "fdr_matrix", "title": "RULE 3: MULTIPLE-TESTING FDR", "subtitle": "BENJAMINI-HOCHBERG CORRECTION ACROSS 28 TESTS"},
    {"id": 95, "name": "s095_fdr_mathematics", "act": 3, "type": "fdr_matrix", "title": "BENJAMINI-HOCHBERG (1995)", "subtitle": "P_{(i)} <= (i / m) * Q_FDR // CONTROLLING FALSE DISCOVERIES"},
    {"id": 96, "name": "s096_rerunning_tournament", "act": 3, "type": "terminal_telemetry", "title": "RERUNNING THE TOURNAMENT", "subtitle": "EXPANDING-WINDOW BACKTEST OVER 292 VALIDATION ORIGINS"},
    {"id": 97, "name": "s097_m2_collapse", "act": 3, "type": "duel_table", "title": "M2 SINGLE-DOMAIN COLLAPSE", "subtitle": "OLD BSS: +0.322 -> HONEST BSS: -0.0056 (ZERO SKILL)"},
    {"id": 98, "name": "s098_fdr_rejection_slaughter", "act": 3, "type": "fdr_matrix", "title": "THE STATISTICAL SLAUGHTER", "subtitle": "25 OUT OF 28 TOURNAMENT HYPOTHESES REJECTED"},
    {"id": 99, "name": "s099_horizon_collapse_7d", "act": 3, "type": "fdr_matrix", "title": "HORIZON = 7 DAYS: COLLAPSE", "subtitle": "ALL 8 MODELS FAIL FDR CONTROL (q >= 0.78)"},
    {"id": 100, "name": "s100_horizon_collapse_14d", "act": 3, "type": "fdr_matrix", "title": "HORIZON = 14 DAYS: COLLAPSE", "subtitle": "PREDICTING 2-WEEK CRYPTO CRASHES = PURE NOISE"},
    {"id": 101, "name": "s101_the_two_survivors", "act": 3, "type": "title_card", "title": "THE ONLY SURVIVORS", "subtitle": "M4 DYNAMIC-AR & M5 LIGHTGBM AT 1-DAY HORIZON"},
    {"id": 102, "name": "s102_m4_stats_card", "act": 3, "type": "duel_table", "title": "M4 DYNAMIC AUTOREGRESSION", "subtitle": "BSS: +0.0756 // DM p = 0.0000 // FDR q = 0.0000 (PASS)"},
    {"id": 103, "name": "s103_m5_stats_card", "act": 3, "type": "duel_table", "title": "M5 LIGHTGBM GBDT", "subtitle": "BSS: +0.2523 // DM p = 0.0040 // FDR q = 0.0373 (PASS)"},
    {"id": 104, "name": "s104_bootstrap_confidence_ci", "act": 3, "type": "kalman", "title": "BOOTSTRAP CONFIDENCE BANDS", "subtitle": "M5 95% CI: [+0.008, +0.416] STRICTLY POSITIVE"},
    {"id": 105, "name": "s105_m7_dlm_failure", "act": 3, "type": "duel_table", "title": "M7 CENTRAL BANK DLM RESULT", "subtitle": "BSS: +0.0030 // DM p = 0.3004 // FDR q = 0.7905 (FAIL)"},
    {"id": 106, "name": "s106_why_m7_failed_direction", "act": 3, "type": "circuit_board", "title": "WHY STATE-SPACE SMOOTHING FAILS", "subtitle": "GAUSSIAN KALMAN ASSUMPTIONS BLUNT NON-LINEAR CRASHES"},
    {"id": 107, "name": "s107_the_cold_truth", "act": 3, "type": "title_card", "title": "THE HONEST VERDICT", "subtitle": "CRYPTO ALPHA LIVES EXCLUSIVELY AT 24 TO 72 HOURS"},
    {"id": 108, "name": "s108_from_stats_to_pnl", "act": 3, "type": "circuit_board", "title": "FROM BRIER SCORE TO REAL P&L", "subtitle": "CAN FORECAST SKILL SAVE A REAL-WORLD PORTFOLIO?"},
    {"id": 109, "name": "s109_simulation_prep", "act": 3, "type": "orderbook", "title": "BUILDING THE HEDGE ENGINE", "subtitle": "INTRODUCING EXCHANGE FRICTION & PERP FUNDING"},
    {"id": 110, "name": "s110_act4_transition", "act": 3, "type": "title_card", "title": "ACT IV // THE WALK-FORWARD HEDGE", "subtitle": "CRUSHING DRAWDOWN WITH SHORT PERPETUALS"},

    # ================================= ACT 4: THE TRUE WALK-FORWARD HEDGE (Scenes 111-135) ===
    {"id": 111, "name": "s111_the_hedging_mandate", "act": 4, "type": "candlestick", "title": "THE HEDGING MANDATE", "subtitle": "100% LONG SPOT BITCOIN // NEVER SELL SPOT (NO TAX EVENT)"},
    {"id": 112, "name": "s112_short_perp_overlay", "act": 4, "type": "circuit_board", "title": "1.0X SHORT PERPETUAL OVERLAY", "subtitle": "PERFECT DELTA-NEUTRAL COVERAGE DURING CRISIS ALERTS"},
    {"id": 113, "name": "s113_exchange_friction_detail", "act": 4, "type": "orderbook", "title": "INSTITUTIONAL FRICTION MODEL", "subtitle": "5 BPS TAKER FEE + 5 BPS SLIPPAGE = 10 BPS PER FLIP"},
    {"id": 114, "name": "s114_funding_cash_flows", "act": 4, "type": "terminal_telemetry", "title": "LIVE PERPETUAL FUNDING", "subtitle": "APPLYING ACTUAL 8-HR CASH FLOWS CREDITED TO SHORT"},
    {"id": 115, "name": "s115_walkforward_simulation_run", "act": 4, "type": "candlestick", "title": "WALK-FORWARD EXECUTION", "subtitle": "292 ROLLING OUT-OF-SAMPLE TRADING DAYS"},
    {"id": 116, "name": "s116_unhedged_baseline_curve", "act": 4, "type": "candlestick", "title": "UNHEDGED BUY & HOLD", "subtitle": "RETURN: +16.48% // MAX DRAWDOWN: 51.32% // SHARPE: 0.26"},
    {"id": 117, "name": "s117_m5_hedged_equity_curve", "act": 4, "type": "candlestick", "title": "M5 LIGHTGBM OVERLAY", "subtitle": "TOTAL RETURN: +420.69% NET // SHARPE: 2.22 // SORTINO: 3.78"},
    {"id": 118, "name": "s118_drawdown_comparison_split", "act": 4, "type": "duel_table", "title": "DRAWDOWN DESTRUCTION HALTED", "subtitle": "UNHEDGED 51.32% -> M5 HEDGED 12.95% (38.38 PP REDUCTION)"},
    {"id": 119, "name": "s119_march_2024_alltime_high", "act": 4, "type": "candlestick", "title": "73K ALL-TIME HIGH CYCLE", "subtitle": "M5 RIDES THE ENTIRE UPTREND FULLY EXPOSED TO SPOT"},
    {"id": 120, "name": "s120_august_crash_shield", "act": 4, "type": "candlestick", "title": "AUGUST 2024 CRASH SHIELD", "subtitle": "HEDGE ACTIVATES AT 0.20 THRESHOLD -> ABSORBS 30% DROP"},
    {"id": 121, "name": "s121_funding_bonus_explained", "act": 4, "type": "terminal_telemetry", "title": "FUNDING HARVEST BONUS", "subtitle": "COLLECTING +5.91% CASH FLOW FROM PANICKED SHORTS"},
    {"id": 122, "name": "s122_m4_autoregression_result", "act": 4, "type": "duel_table", "title": "M4 DYNAMIC-AR RESULT", "subtitle": "RETURN: +353.29% // MAX DRAWDOWN: 21.68% // SHARPE: 1.78"},
    {"id": 123, "name": "s123_m7_central_bank_flop", "act": 4, "type": "duel_table", "title": "M7 FULL 4D DLM RESULT", "subtitle": "RETURN: +48.69% // MAX DRAWDOWN: 51.32% (ZERO PROTECTION)"},
    {"id": 124, "name": "s124_why_m7_failed_hedge", "act": 4, "type": "circuit_board", "title": "THE SMOOTHING CASUALTY", "subtitle": "M7 NEVER CROSSED 0.20 DURING RAPID INTRADAY DRAINS"},
    {"id": 125, "name": "s125_leaderboard_inspection", "act": 4, "type": "terminal_telemetry", "title": "INSPECTING THE LEADERBOARD", "subtitle": "SORTING NET RETURNS ACROSS ALL 8 ENGINES"},
    {"id": 126, "name": "s126_anomaly_spotted", "act": 4, "type": "title_card", "title": "WAIT... WHAT IS THAT?", "subtitle": "M0 PERSISTENCE RANKS NUMBER ONE IN RETURN"},
    {"id": 127, "name": "s127_m0_persistence_stats", "act": 4, "type": "duel_table", "title": "M0 PERSISTENCE NUMBERS", "subtitle": "TOTAL RETURN: +477.79% // MAX DRAWDOWN: 12.89%"},
    {"id": 128, "name": "s128_humiliation_of_ai", "act": 4, "type": "title_card", "title": "DID A DUMB RULE BEAT AI?", "subtitle": "ZERO TREES // ZERO KALMAN FILTERS // +57% HIGHER RETURN"},
    {"id": 129, "name": "s129_friction_drag_column", "act": 4, "type": "terminal_telemetry", "title": "THE COST OF INDECISION", "subtitle": "LOOK AT THE FRICTION DRAG COLUMN IN THE REPORT"},
    {"id": 130, "name": "s130_fee_bleeding_breakdown", "act": 4, "type": "orderbook", "title": "FEE BLEEDING DISCOVERED", "subtitle": "M5 FLIPPED 56 TIMES -> 16.37% CAPITAL BURNED IN FEES"},
    {"id": 131, "name": "s131_persistence_calm", "act": 4, "type": "candlestick", "title": "PERSISTENCE DISCIPLINE", "subtitle": "M0 FLIPPED ONLY 38 TIMES -> ONLY 10.14% FRICTION DRAG"},
    {"id": 132, "name": "s132_whipsaw_oscilloscope", "act": 4, "type": "hysteresis", "title": "HAIRLINE WHIPSAWS", "subtitle": "PROBABILITY FLICKERING AT 19.9% VS 20.1%"},
    {"id": 133, "name": "s133_mandelbrot_vindication", "act": 4, "type": "circuit_board", "title": "MANDELBROT WAS RIGHT", "subtitle": "CRYPTO VOLATILITY OCCURS IN CONTINUOUS REGIME BLOCKS"},
    {"id": 134, "name": "s134_the_deep_dive_begins", "act": 4, "type": "title_card", "title": "IS PERSISTENCE TRULY KING?", "subtitle": "TESTING PARAMETER SENSITIVITY ACROSS THRESHOLDS"},
    {"id": 135, "name": "s135_act5_transition", "act": 4, "type": "title_card", "title": "ACT V // THE ONE-BIT TRAP", "subtitle": "WHY M0 IS AN ILLUSION & HOW HYSTERESIS SAVES AI"},

    # ================================= ACT 5: THE ONE-BIT TRAP & HYSTERESIS (Scenes 136-155) ===
    {"id": 136, "name": "s136_sensitivity_sweep_grid", "act": 5, "type": "radar_gauge", "title": "THRESHOLD SENSITIVITY SWEEP", "subtitle": "SWEEPING THRESHOLDS theta FROM 0.10 TO 0.40"},
    {"id": 137, "name": "s137_m0_frozen_anomaly", "act": 5, "type": "duel_table", "title": "THE M0 FROZEN ANOMALY", "subtitle": "RETURN IS 477.79% AT 0.10, 0.20, 0.30, AND 0.40!"},
    {"id": 138, "name": "s138_zero_elasticity_revealed", "act": 5, "type": "circuit_board", "title": "ZERO THRESHOLD ELASTICITY", "subtitle": "NOT A SINGLE FLIP OR BASIS POINT CHANGES WITH theta"},
    {"id": 139, "name": "s139_code_dissection_m0", "act": 5, "type": "terminal_telemetry", "title": "INSPECTING CRYPTO_BASELINES.PY", "subtitle": "decay = exp(-0.05 * (h - 1)) // AT h=1 -> decay = 1.0"},
    {"id": 140, "name": "s140_the_one_bit_formula", "act": 5, "type": "circuit_board", "title": "THE 1-BIT COLLAPSE", "subtitle": "p = last_state in {0.01, 0.99} // NO PROBABILITY CONTINUUM"},
    {"id": 141, "name": "s141_the_light_switch_analogy", "act": 5, "type": "title_card", "title": "A BROKEN LIGHT SWITCH", "subtitle": "PERSISTENCE CANNOT BE RISK-MANAGED OR CALIBRATED"},
    {"id": 142, "name": "s142_m0_fdr_failure_recall", "act": 5, "type": "fdr_matrix", "title": "REMEMBER THE FDR TEST?", "subtitle": "M0 FAILED DIEBOLD-MARIANO SIGNIFICANCE (q = 0.4578)"},
    {"id": 143, "name": "s143_m5_plateau_chart", "act": 5, "type": "candlestick", "title": "THE M5 ROBUSTNESS PLATEAU", "subtitle": "32% TO 39% DRAWDOWN REDUCTION ACROSS [0.10, 0.30]"},
    {"id": 144, "name": "s144_m5_tunable_dial", "act": 5, "type": "radar_gauge", "title": "THE ONLY TUNABLE RISK ENGINE", "subtitle": "M5 GIVES PORTFOLIO MANAGERS A CONTINUOUS CONTROLLER"},
    {"id": 145, "name": "s145_baseline_inertia_explained", "act": 5, "type": "circuit_board", "title": "BASELINE COMPRESSION", "subtitle": "M1, M2, M3, M6, M7 GO INERT AT theta >= 0.25 (0% HEDGE)"},
    {"id": 146, "name": "s146_schmitt_trigger_diagram", "act": 5, "type": "hysteresis", "title": "SCHMITT TRIGGER LOGIC", "subtitle": "ENTER HEDGE: P >= 0.25 // EXIT HEDGE: P <= 0.15"},
    {"id": 147, "name": "s147_hysteresis_oscilloscope_run", "act": 5, "type": "hysteresis", "title": "TAMING THE FLICKER", "subtitle": "SIGNALS INSIDE DEAD-BAND [0.15, 0.25] CANNOT FLIP"},
    {"id": 148, "name": "s148_flips_slashed_46", "act": 5, "type": "orderbook", "title": "10 FLIPS ELIMINATED", "subtitle": "FLIP COUNT DROPS FROM 56 DOWN TO 46"},
    {"id": 149, "name": "s149_friction_saved_379", "act": 5, "type": "terminal_telemetry", "title": "+3.79% FRICTION DRAG SAVED", "subtitle": "FEES REDUCED FROM 16.37% TO 12.58% NET"},
    {"id": 150, "name": "s150_drawdown_untouched", "act": 5, "type": "duel_table", "title": "12.95% DRAWDOWN PRESERVED", "subtitle": "ZERO BASIS POINTS OF PROTECTION LOST IN HYSTERESIS"},
    {"id": 151, "name": "s151_sortino_ratio_strength", "act": 5, "type": "terminal_telemetry", "title": "SORTINO RATIO: 3.41", "subtitle": "EXCEPTIONAL DOWNSIDE-DEVIATION EFFICIENCY"},
    {"id": 152, "name": "s152_tesseract_stabilized", "act": 5, "type": "tesseract", "title": "THE 4D HYPER-TOLERANCE", "subtitle": "MATHEMATICAL STRUCTURE PARED WITH EXECUTION CONTROL"},
    {"id": 153, "name": "s153_engineering_meets_math", "act": 5, "type": "circuit_board", "title": "THE QUANT SYNTHESIS", "subtitle": "AI STATISTICAL EDGE + ELECTRICAL ENGINEERING HYSTERESIS"},
    {"id": 154, "name": "s154_summary_comparison_master", "act": 5, "type": "duel_table", "title": "MASTER RESULTS MATRIX", "subtitle": "UNHEDGED (51.3% DD) VS M5 HYST (12.95% DD / +363% RETURN)"},
    {"id": 155, "name": "s155_act6_transition", "act": 5, "type": "title_card", "title": "ACT VI // THE CODA & VERDICT", "subtitle": "WHAT DOES THIS MEAN FOR LIVE CAPITAL?"},

    # ================================= ACT 6: CODA & THE VERDICT (Scenes 156-165) ===
    {"id": 156, "name": "s156_institutional_verdict", "act": 6, "type": "title_card", "title": "THE INSTITUTIONAL VERDICT", "subtitle": "THREE LESSONS FROM 970 DAYS OF REAL CRYPTO DATA"},
    {"id": 157, "name": "s157_lesson_1_m7_role", "act": 6, "type": "radar_gauge", "title": "LESSON 1: THE SIMULATOR", "subtitle": "M7 IS A MACRO STRESS-TEST ENGINE, NOT A TRADE TRIGGER"},
    {"id": 158, "name": "s158_girf_irreplaceable", "act": 6, "type": "contagion", "title": "IRF NETWORK VALUATION", "subtitle": "ESSENTIAL FOR DEFI TREASURY & LIQUIDATION MODELING"},
    {"id": 159, "name": "s159_lesson_2_horizon_limit", "act": 6, "type": "circuit_board", "title": "LESSON 2: 1-DAY BOUNDARY", "subtitle": "PREDICTING 7-DAY CRASHES USING PUBLIC DATA IS FICTION"},
    {"id": 160, "name": "s160_lesson_3_execution_king", "act": 6, "type": "orderbook", "title": "LESSON 3: EXECUTION IS KING", "subtitle": "FRICTION & HYSTERESIS SEPARATE LIVE ALPHA FROM RUIN"},
    {"id": 161, "name": "s161_github_open_science", "act": 6, "type": "terminal_telemetry", "title": "100% REPRODUCIBLE CODEBASE", "subtitle": "GITHUB: 31 UNIT TESTS // SQLITE PIT DB // OPEN HEDGE ENGINE"},
    {"id": 162, "name": "s162_clone_and_verify", "act": 6, "type": "circuit_board", "title": "VERIFY FOR YOURSELF", "subtitle": "NO BLACK BOXES // NO FABRICATED CURVES // TRUE QUANT SCIENCE"},
    {"id": 163, "name": "s163_channel_mission", "act": 6, "type": "title_card", "title": "THE IZHAAN INTELLECT PROMISE", "subtitle": "UNCOMPROMISING MATHEMATICAL HONESTY & VISUAL EXCELLENCE"},
    {"id": 164, "name": "s164_tesseract_final_dissolve", "act": 6, "type": "tesseract", "title": "BEYOND THE THIRD DIMENSION", "subtitle": "THE NEXT FRONTIER OF THEORETICAL FINANCE"},
    {"id": 165, "name": "s165_outro_community", "act": 6, "type": "channel_ident", "title": "SUBSCRIBE TO IZHAAN INTELLECT", "subtitle": "JOIN THE VANGUARD OF HIGHER-DIMENSIONAL SCIENCE"}
]
